GET http://localhost:5000/auth/register

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "firstName": "admin",
    "dateOfBirth": "2001-07-09",
    "idNumber": "1234567891011",
    "username": "admin",
    "email": "admin@lorettabank.com",
    "password": "password"
}

###
GET http://localhost:5000/auth/login

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "password"
}

